<?php

namespace RgkBundle\Repository;

/**
 * RivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RivalRepository extends \Doctrine\ORM\EntityRepository
{
}
